include ../config.mk

# use global gm-study-e1 board hardware definition file
PRFLAGS += -ccf ../gatemate.ccf
#PRFLAGS += -ccf /home/fm/fpga/hardware/gm-proto-e1/examples-tht/pmod_charlcd/src/gm-pmod.ccf
#PRFLAGS += -ccf /home/fm/fpga/hardware/gm-proto-e1/examples-tht/pmod_charlcd/src/gm-max.ccf

TOP = display
